var tplMemberDetail = new Ext.XTemplate(
	'<tpl for=".">',
	    '<div class="userInfoBox rounded">',
			'<div class="data">',
				'<div class="label"><label for={uyeNo}>Üye Numarası:</label></div>',
				'<div class="info">{uyeNo}</div>',
				'<br style="clear: both;" />',
			'</div>',
			'<div class="data">',
				'<div class="label"><label for={paraBirimi}>Para Birimi:</label></div>',
				'<div class="info">{paraBirimi}</div>',
				'<br style="clear: both;" />',
			'</div>',
			'<div class="data">',
				'<div class="label"><label for={kimlikNo}>Kimlik Numarası:</label></div>',
				'<div class="info">{kimlikNo}</div>',
				'<br style="clear: both;" />',
			'</div>',
			'<div class="data">',
				'<div class="label"><label for={firstName}>İsim:</label></div>',
				'<div class="info">{firstName}</div>',
				'<br style="clear: both;" />',
			'</div>',
			'<div class="data">',
				'<div class="label"><label for={lastName}>Soyisim:</label></div>',
				'<div class="info">{lastName}</div>',
				'<br style="clear: both;" />',
			'</div>',
			'<div class="data">',
				'<div class="label"><label for={dob}>Doğum Tarihi:</label></div>',
				'<div class="info">{dob}</div>',
				'<br style="clear: both;" />',
			'</div>',
			'<div class="data">',
				'<div class="label"><label for={city}>Yerleşik Ülke:</label></div>',
				'<div class="info">{ulke}</div>',
				'<br style="clear: both;" />',
			'</div>',
		'</div>',
    '</tpl>'
);